module.exports = {
  name: 'AntD Admin',
  prefix: 'antdAdmin',
  footerText: 'Ant Design Admin  © 2017 zuiidea',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:9000',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://192.168.1.117:8081'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/api/v1/auth',
    userLogout: '/user/logout',
    userInfo: '/api/v1/user',
    users: '/users',
    posts: '/posts',
    user: '/api/v1/user',
    dashboard: '/dashboard',
    record: '/record/query',
    flow: '/record-flow',
  },
}
