module.exports = {
  name: '稻壳',
  prefix: 'antdAdmin',
  footerText: 'Ant Design Admin  © 2017 zuiidea',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:9000',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:8085'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/api/v1/auth',
    userLogout: '/user/logout',
    userInfo: '/api/v1/user',
    users: '/users',
    posts: '/posts',
    user: '/api/v1/user',
    dashboard: '/dashboard',
    record: '/api/v1/orders',
    flow: '/api/v1/record-flow',
    contact: '/api/v1/contactinfo',
    contacts: '/api/v1/contactinfos',
  },
}
